CREATE OR ALTER  PROCEDURE [Prod].[UDP_tbLotes_Materiales] --'CW20230827'
(
	@lote_CodigoLote NVARCHAR(40)
)
AS
BEGIN
	SELECT	lote_Id,
			tblotes.lote_CodigoLote,
			tblotes.mate_Id,
			mate_Descripcion,
			tblotes.lote_Stock,
			tbarea.tipa_area,
			tbcolo.colr_Id,
			tbcolo.colr_Nombre
	FROM Prod.tbLotes tblotes			
			INNER JOIN Prod.tbMateriales tbmats		ON tblotes.mate_Id = tbmats.mate_Id
			INNER JOIN Prod.tbArea	tbarea			ON tblotes.tipa_Id = tbarea.tipa_Id
			LEFT JOIN Prod.tbColores tbcolo			ON tblotes.colr_Id = tbcolo.colr_Id
	WHERE tblotes.lote_CodigoLote = @lote_CodigoLote
END
GO

SET IDENTITY_INSERT [Adua].[tbMarcas] ON 
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (1, N'Toyota', 1, CAST(N'2022-04-30T00:00:00.000' AS DateTime), 2, CAST(N'2023-08-30T21:46:20.000' AS DateTime), NULL, NULL, 1)
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (2, N'BMW', 1, CAST(N'2022-04-30T00:00:00.000' AS DateTime), NULL, NULL, NULL, NULL, 1)
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (3, N'Volkswagen', 1, CAST(N'2022-01-08T00:00:00.000' AS DateTime), 2, CAST(N'2023-08-30T21:49:30.000' AS DateTime), NULL, NULL, 1)
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (4, N'Hyundai', 1, CAST(N'2022-03-21T00:00:00.000' AS DateTime), NULL, NULL, NULL, NULL, 1)
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (5, N'Chevrolet', 1, CAST(N'2022-08-30T00:00:00.000' AS DateTime), NULL, NULL, NULL, NULL, 1)
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (6, N'Honda', 1, CAST(N'2022-02-10T00:00:00.000' AS DateTime), NULL, NULL, 2, CAST(N'2023-08-29T13:57:17.000' AS DateTime), 0)
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (7, N'Nissan', 1, CAST(N'2022-02-07T00:00:00.000' AS DateTime), 2, CAST(N'2023-08-29T11:09:36.000' AS DateTime), NULL, NULL, 1)
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (8, N'Nissan3', 2, CAST(N'2023-08-29T10:59:34.000' AS DateTime), 2, CAST(N'2023-08-29T11:08:31.000' AS DateTime), 2, CAST(N'2023-08-29T11:08:53.000' AS DateTime), 0)
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (23, N'Toyota V23', 2, CAST(N'2023-08-29T13:55:24.000' AS DateTime), 2, CAST(N'2023-08-29T13:55:43.000' AS DateTime), 2, CAST(N'2023-08-29T13:57:25.000' AS DateTime), 0)
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (24, N'4', 2, CAST(N'2023-08-29T14:21:53.000' AS DateTime), NULL, NULL, 2, CAST(N'2023-08-29T14:21:56.000' AS DateTime), 0)
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (27, N'Prueba', 2, CAST(N'2023-08-30T21:48:42.000' AS DateTime), NULL, NULL, 2, CAST(N'2023-08-30T21:48:48.000' AS DateTime), 0)
INSERT [Adua].[tbMarcas] ([marc_Id], [marc_Descripcion], [usua_UsuarioCreacion], [marc_FechaCreacion], [usua_UsuarioModificacion], [marc_FechaModificacion], [usua_UsuarioEliminacion], [marc_FechaEliminacion], [marc_Estado]) VALUES (31, N'Ferrari', 2, CAST(N'2023-09-01T08:31:24.000' AS DateTime), NULL, NULL, 2, CAST(N'2023-09-01T08:31:18.000' AS DateTime), 1)
SET IDENTITY_INSERT [Adua].[tbMarcas] OFF
GO

SET IDENTITY_INSERT [Adua].[tbModoTransporte] ON 
INSERT [Adua].[tbModoTransporte] ([motr_Id], [motr_Descripcion], [usua_UsuarioCreacion], [motr_FechaCreacion], [usua_UsuarioModificacion], [motr_FechaModificacion], [usua_UsuarioEliminacion], [motr_FechaEliminacion], [motr_Estado]) VALUES (1, N'Marítimo', 1, CAST(N'2023-08-22T03:27:55.107' AS DateTime), 2, CAST(N'2023-08-29T14:00:47.000' AS DateTime), NULL, NULL, 1)
INSERT [Adua].[tbModoTransporte] ([motr_Id], [motr_Descripcion], [usua_UsuarioCreacion], [motr_FechaCreacion], [usua_UsuarioModificacion], [motr_FechaModificacion], [usua_UsuarioEliminacion], [motr_FechaEliminacion], [motr_Estado]) VALUES (2, N'Aéreo', 1, CAST(N'2023-08-22T03:27:55.107' AS DateTime), NULL, NULL, NULL, NULL, 1)
INSERT [Adua].[tbModoTransporte] ([motr_Id], [motr_Descripcion], [usua_UsuarioCreacion], [motr_FechaCreacion], [usua_UsuarioModificacion], [motr_FechaModificacion], [usua_UsuarioEliminacion], [motr_FechaEliminacion], [motr_Estado]) VALUES (3, N'Terrestre', 1, CAST(N'2023-08-22T03:27:55.107' AS DateTime), NULL, NULL, NULL, NULL, 1)
INSERT [Adua].[tbModoTransporte] ([motr_Id], [motr_Descripcion], [usua_UsuarioCreacion], [motr_FechaCreacion], [usua_UsuarioModificacion], [motr_FechaModificacion], [usua_UsuarioEliminacion], [motr_FechaEliminacion], [motr_Estado]) VALUES (4, N'Fluvial', 1, CAST(N'2023-08-22T03:27:55.107' AS DateTime), NULL, NULL, NULL, NULL, 1)
INSERT [Adua].[tbModoTransporte] ([motr_Id], [motr_Descripcion], [usua_UsuarioCreacion], [motr_FechaCreacion], [usua_UsuarioModificacion], [motr_FechaModificacion], [usua_UsuarioEliminacion], [motr_FechaEliminacion], [motr_Estado]) VALUES (10, N'mar', 2, CAST(N'2023-08-29T14:20:50.000' AS DateTime), 2, CAST(N'2023-08-29T14:21:37.000' AS DateTime), NULL, NULL, 1)
INSERT [Adua].[tbModoTransporte] ([motr_Id], [motr_Descripcion], [usua_UsuarioCreacion], [motr_FechaCreacion], [usua_UsuarioModificacion], [motr_FechaModificacion], [usua_UsuarioEliminacion], [motr_FechaEliminacion], [motr_Estado]) VALUES (14, N'mare', 2, CAST(N'2023-08-29T14:58:17.000' AS DateTime), 2, CAST(N'2023-08-29T14:59:42.000' AS DateTime), NULL, NULL, 1)
INSERT [Adua].[tbModoTransporte] ([motr_Id], [motr_Descripcion], [usua_UsuarioCreacion], [motr_FechaCreacion], [usua_UsuarioModificacion], [motr_FechaModificacion], [usua_UsuarioEliminacion], [motr_FechaEliminacion], [motr_Estado]) VALUES (22, N'Marítim2', 2, CAST(N'2023-09-01T08:40:26.000' AS DateTime), NULL, NULL, NULL, NULL, 1)
SET IDENTITY_INSERT [Adua].[tbModoTransporte] OFF
GO

SET IDENTITY_INSERT [Gral].[tbOficinas] ON 
INSERT [Gral].[tbOficinas] ([ofic_Id], [ofic_Nombre], [usua_UsuarioCreacion], [ofic_FechaCreacion], [usua_UsuarioModificacion], [ofic_FechaModificacion], [usua_UsuarioEliminacion], [ofic_FechaEliminacion], [ofic_Estado]) VALUES (1, N'TEGUCIGALPA, M.D.C.', 1, CAST(N'2023-08-22T03:26:59.963' AS DateTime), NULL, NULL, NULL, NULL, 1)
INSERT [Gral].[tbOficinas] ([ofic_Id], [ofic_Nombre], [usua_UsuarioCreacion], [ofic_FechaCreacion], [usua_UsuarioModificacion], [ofic_FechaModificacion], [usua_UsuarioEliminacion], [ofic_FechaEliminacion], [ofic_Estado]) VALUES (2, N'SAN PEDRO SULA, CORTÉS', 1, CAST(N'2023-08-22T03:26:59.963' AS DateTime), NULL, NULL, NULL, NULL, 1)
INSERT [Gral].[tbOficinas] ([ofic_Id], [ofic_Nombre], [usua_UsuarioCreacion], [ofic_FechaCreacion], [usua_UsuarioModificacion], [ofic_FechaModificacion], [usua_UsuarioEliminacion], [ofic_FechaEliminacion], [ofic_Estado]) VALUES (3, N'PRUEBA PPA', 2, CAST(N'2023-08-22T10:37:07.000' AS DateTime), 2, CAST(N'2023-08-22T10:37:59.000' AS DateTime), 2, CAST(N'2023-08-22T10:38:13.000' AS DateTime), 0)
INSERT [Gral].[tbOficinas] ([ofic_Id], [ofic_Nombre], [usua_UsuarioCreacion], [ofic_FechaCreacion], [usua_UsuarioModificacion], [ofic_FechaModificacion], [usua_UsuarioEliminacion], [ofic_FechaEliminacion], [ofic_Estado]) VALUES (5, N'OFICINA DE PRUEBA OWO', 2, CAST(N'2023-08-31T13:24:37.000' AS DateTime), NULL, NULL, 2, CAST(N'2023-08-31T13:32:43.000' AS DateTime), 0)
INSERT [Gral].[tbOficinas] ([ofic_Id], [ofic_Nombre], [usua_UsuarioCreacion], [ofic_FechaCreacion], [usua_UsuarioModificacion], [ofic_FechaModificacion], [usua_UsuarioEliminacion], [ofic_FechaEliminacion], [ofic_Estado]) VALUES (8, N'OFICINA', 2, CAST(N'2023-08-31T15:48:10.000' AS DateTime), 2, CAST(N'2023-08-31T15:48:17.000' AS DateTime), 2, CAST(N'2023-08-31T15:56:25.000' AS DateTime), 0)
INSERT [Gral].[tbOficinas] ([ofic_Id], [ofic_Nombre], [usua_UsuarioCreacion], [ofic_FechaCreacion], [usua_UsuarioModificacion], [ofic_FechaModificacion], [usua_UsuarioEliminacion], [ofic_FechaEliminacion], [ofic_Estado]) VALUES (9, N'LA CEIBA', 2, CAST(N'2023-08-31T15:54:52.000' AS DateTime), NULL, NULL, 2, CAST(N'2023-08-31T15:55:34.000' AS DateTime), 1)
SET IDENTITY_INSERT [Gral].[tbOficinas] OFF
GO

SET IDENTITY_INSERT [Gral].[tbOficio_Profesiones] ON 
INSERT [Gral].[tbOficio_Profesiones] ([ofpr_Id], [ofpr_Nombre], [usua_UsuarioCreacion], [ofpr_FechaCreacion], [usua_UsuarioModificacion], [ofpr_FechaModificacion], [ofpr_Estado]) VALUES (1, N'OFICIALES DE LAS FUERZAS ARMADAS', 1, CAST(N'2023-08-22T03:27:00.027' AS DateTime), 3, CAST(N'2023-08-23T11:31:05.000' AS DateTime), 1)
INSERT [Gral].[tbOficio_Profesiones] ([ofpr_Id], [ofpr_Nombre], [usua_UsuarioCreacion], [ofpr_FechaCreacion], [usua_UsuarioModificacion], [ofpr_FechaModificacion], [ofpr_Estado]) VALUES (2, N'SUBOFICIALES DE LAS FUERZAS ARMADAS', 1, CAST(N'2023-08-22T03:27:00.027' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbOficio_Profesiones] ([ofpr_Id], [ofpr_Nombre], [usua_UsuarioCreacion], [ofpr_FechaCreacion], [usua_UsuarioModificacion], [ofpr_FechaModificacion], [ofpr_Estado]) VALUES (3, N'OTROS MIEMBROS DE LAS FUERZAS ARMADAS', 1, CAST(N'2023-08-22T03:27:00.027' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbOficio_Profesiones] ([ofpr_Id], [ofpr_Nombre], [usua_UsuarioCreacion], [ofpr_FechaCreacion], [usua_UsuarioModificacion], [ofpr_FechaModificacion], [ofpr_Estado]) VALUES (4, N'MIEMBROS DEL PODER EJECUTIVO Y DE LOS CUERPOS LEGISLATIVOS', 1, CAST(N'2023-08-22T03:27:00.027' AS DateTime), NULL, NULL, 1)
SET IDENTITY_INSERT [Gral].[tbOficio_Profesiones] OFF
GO

SET IDENTITY_INSERT [Gral].[tbMonedas] ON 
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (1, N'EUR', N'COMUNIDAD EUROPEA, EURO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (2, N'HNL', N'HONDURAS, LEMPIRA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (3, N'USD', N'DOLAR NORTEAMERICANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), 2, CAST(N'2023-08-23T11:24:04.000' AS DateTime), 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (4, N'AED', N'EMIRATOS ARABES UNIDOS, DIRHAM', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (5, N'AFN', N'AFGANISTAN, AFGANI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (6, N'ALL', N'ALBANIA, LEK', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (7, N'AMD', N'ARMENIA, DRAM ARMENIO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (8, N'ANG', N'HOLANDESAS ANTILLAS, FLORIN ANTILLANO NEERLANDES', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (9, N'AOA', N'ANGOLA, KWANZA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (10, N'ARS', N'ARGENTINA, PESO ARGENTINO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (11, N'AUD', N'AUSTRALIA, DOLAR AUSTRALIANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (12, N'AWG', N'ARUBA, FLORIN ARUBEÑO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (13, N'AZN', N'AZERBALIAN, MANAT AZERBAIYANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (14, N'BAM', N'BOSNIA HERZSEGOVINA, MARCO CONVERTIBLE', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (15, N'BBD', N'BARBADOS, DOLAR DE BARBADOS', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (16, N'BDT', N'BANGLADESH, TAKA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (17, N'BGN', N'BULGARIA, LEV BULGARO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (18, N'BHD', N'BAHREIN, DINAR BAREINI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (19, N'BIF', N'BURUNDI, FRANCO DE BURUNDI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (20, N'BMD', N'BARMUDA, DOLAR BERMUDEÑO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (21, N'BND', N'BRUNEI, DOLAR DE BRUNEI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (22, N'BOB', N'BOLIVIA, BOLIVIANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (23, N'BRL', N'BRASIL, REAL BRASILEÑO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (24, N'BSD', N'BAHAMAS, DOLAR BAHAMEÑO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (25, N'BTN', N'BUTAN, NGULTRUM', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (26, N'BWP', N'BOTSWANA, PULA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (27, N'BYR', N'BIELORRUSIA, RUBLO BIELORRUSO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (28, N'BZD', N'BELICE, DOLAR BELICEÑO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (29, N'CAD', N'CANADA, DOLAR CANADIENSE', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (30, N'CDF', N'CONGO, REPUBLICA DEMOCRATICA, FRANCO CONGOLEÑO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (31, N'CHF', N'SUIZA, FRANCO SUIZO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (32, N'CLP', N'CHILE, PESO CHILENO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (33, N'CNY', N'CHINA, YUAN CHINO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (34, N'COP', N'COLOMBIA, PESO COLOMBIANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (35, N'CRC', N'COSTA RICA, COLON COSTARRICENSE', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (36, N'CUC', N'CUBA, PESO CONVERTIBLE', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (37, N'CUP', N'CUBA, PESO CUBANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (38, N'CVE', N'CABO VERDE, ESCUDO CABOVERDIANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (39, N'CZK', N'CHECA REPUBLICA, CORONA CHECA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (40, N'DJF', N'DJIBOUTH, FRANCO YIBUTIANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (41, N'DKK', N'DINAMARCA, CORONA DANESA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (42, N'DOP', N'DOMINICANA REPUBLICA, PESO DOMINICANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (43, N'DZD', N'ARGELIA, DINAR ARGELINO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (44, N'EGP', N'EGIPTO, LIBRA EGIPCIA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (45, N'ERN', N'ERITREA, NAKFA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (46, N'ETB', N'ETIOPIA, BIRR ETIOPE', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (47, N'FJD', N'FIJI, DOLAR FIYIANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (48, N'FKP', N'ISLAS MALVINAS, LIBRA MALVINENSE', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (49, N'GBP', N'REINO UNIDO, LIBRA ESTERLINA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (50, N'GEL', N'GEORGIA, LARI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (51, N'GHS', N'GHANA, CEDI GHANES', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (52, N'GIP', N'GIBRALTAR, LIBRA DE GIBRALTAR', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (53, N'GMD', N'GAMBIA, DALASI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (54, N'GNF', N'GUINEA, FRANCO GUINEANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (55, N'GTQ', N'GUATEMALA, QUETZAL', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (56, N'GYD', N'GUYANA, DOLAR GUYANES', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (57, N'HKD', N'HONG KONG, DOLAR DE HONG KONG', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (58, N'HRK', N'CROACIA, KUNA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (59, N'HTG', N'HAITI, GOURDE', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (60, N'HUF', N'HUNGRIA, FORINTO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (61, N'IDR', N'INDONESIA, RUPIA INDONESIA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (62, N'ILS', N'ISRAEL, NUEVO SHEQUEL ISRAELI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (63, N'INR', N'INDIA, RUPIA INDIA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (64, N'IQD', N'IRAQ, DINAR IRAQUI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (65, N'IRR', N'IRAN, RIAL IRANI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (66, N'ISK', N'ISLANDIA, CORONA ISLANDESA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (67, N'JMD', N'JAMAICA, DOLAR JAMAIQUINO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (68, N'JOD', N'JORDANIA, DINAR JORDANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (69, N'JPY', N'JAPON, YEN', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (70, N'KES', N'KENIA, CHELIN KENIANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (71, N'KGS', N'KIRGHIZISTAN, SOM', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (72, N'KHR', N'CAMBOYA, RIEL', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (73, N'KMF', N'COMORES, FRANCO COMORENSE', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (74, N'KPW', N'KOREA, REPUBLICA POPULAR, WON NORCOREANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (75, N'KRW', N'KOREA, REPUBLICA DEMOCRATICA, WON', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (76, N'KWD', N'KUWAIT, DINAR KUWAITI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (77, N'KYD', N'CAIMAN ISLAS, DOLAR DE LAS ISLAS CAIMAN', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (78, N'KZT', N'KAZAKSTAN, TENGE', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (79, N'LAK', N'LAOS, REPUBLICA POPULAR DEMOCRATICA, KIP', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (80, N'LBP', N'LIBANO, LIBRA LIBANESA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (81, N'LKR', N'SRI LANKA, RUPIA DE SRI LANKA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (82, N'LRD', N'LIBERIA, DOLAR LIBERIANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (83, N'LSL', N'LESOTHO, LOTI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (84, N'LYD', N'LIBIA ARABE, DINAR LIBIO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (85, N'MAD', N'MARRUECOS, DIRHAM MARROQUI', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (86, N'MDL', N'MOLDAVIA, REPUBLICA DE, LEU MOLDAVO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (87, N'MGA', N'MADAGASCAR, ARIARY MALGACHE', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (88, N'MKD', N'MACEDONIA, DENAR', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (89, N'MMK', N'MYANMA, KYAT', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (90, N'MNT', N'MONGOLIA, TUGRIK', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (91, N'MOP', N'MACAU, PATACA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (92, N'MRO', N'MAURITANIA, UQUIYA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (93, N'MUR', N'MAURICIOS, RUPIA DE MAURICIO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (94, N'MVR', N'MALDIVAS, RUFIYAA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (95, N'MWK', N'MALAWI, KWACHA', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (96, N'MXN', N'MEXICO, PESO MEXICANO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (97, N'MYR', N'MALASIA, RINGGIT MALAYO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (98, N'MZN', N'MOZAMBIQUE, METICAL MOZAMBIQUEÑO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbMonedas] ([mone_Id], [mone_Codigo], [mone_Descripcion], [mone_EsAduana], [usua_UsuarioCreacion], [mone_FechaCreacion], [usua_UsuarioModificacion], [mone_FechaModificacion], [mone_Estado]) VALUES (99, N'NAD', N'NAMIBIA, DOLAR NAMIBIO', 1, 1, CAST(N'2023-08-22T03:27:01.037' AS DateTime), NULL, NULL, 1)
GO


SET IDENTITY_INSERT [Gral].[tbProveedores] ON 
INSERT [Gral].[tbProveedores] ([prov_Id], [prov_NombreCompania], [prov_NombreContacto], [prov_Telefono], [prov_CodigoPostal], [prov_Ciudad], [prov_DireccionExacta], [prov_CorreoElectronico], [prov_Fax], [usua_UsuarioCreacion], [prov_FechaCreacion], [usua_UsuarioModificacion], [prov_FechaModificacion], [usua_UsuarioEliminacion], [prov_FechaEliminacion], [prov_Estado]) VALUES (1, N'ECOMODA', N'BEATRIZ PINZON ZOLANO', N'+504 9815-9299', N'21004', 1, N'--------', N'is@hotmail.com', NULL, 1, CAST(N'2023-08-22T03:27:01.277' AS DateTime), NULL, NULL, NULL, NULL, 1)
INSERT [Gral].[tbProveedores] ([prov_Id], [prov_NombreCompania], [prov_NombreContacto], [prov_Telefono], [prov_CodigoPostal], [prov_Ciudad], [prov_DireccionExacta], [prov_CorreoElectronico], [prov_Fax], [usua_UsuarioCreacion], [prov_FechaCreacion], [usua_UsuarioModificacion], [prov_FechaModificacion], [usua_UsuarioEliminacion], [prov_FechaEliminacion], [prov_Estado]) VALUES (2, N'ModaTela', N'Cristian Aguilar', N'+504 8824-7416', N'564', 299, N'werwer fdfg', N'caguillarzuniga7@gmail.com', N'233', 3, CAST(N'2023-08-22T12:38:09.000' AS DateTime), 3, CAST(N'2023-08-25T09:03:52.000' AS DateTime), NULL, NULL, 1)
INSERT [Gral].[tbProveedores] ([prov_Id], [prov_NombreCompania], [prov_NombreContacto], [prov_Telefono], [prov_CodigoPostal], [prov_Ciudad], [prov_DireccionExacta], [prov_CorreoElectronico], [prov_Fax], [usua_UsuarioCreacion], [prov_FechaCreacion], [usua_UsuarioModificacion], [prov_FechaModificacion], [usua_UsuarioEliminacion], [prov_FechaEliminacion], [prov_Estado]) VALUES (3, N'Hola', N'23', N'+504 2342-3423', N'234', 299, N'234', N'caguillarzuniga7@gmail.com', N'', 3, CAST(N'2023-08-22T13:20:28.000' AS DateTime), NULL, NULL, 3, CAST(N'2023-08-22T13:20:31.000' AS DateTime), 0)
SET IDENTITY_INSERT [Gral].[tbProveedores] OFF
GO