// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIMEXPRO.Entities.Entities
{
    public partial class tbProcesoPorOrdenCompraDetalle
    {
        public int poco_Id { get; set; }
        public int code_Id { get; set; }
        public int proc_Id { get; set; }
        [NotMapped]
        public string proc_Descripcion { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime poco_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? poco_FechaModificacion { get; set; }
        public bool? code_Estado { get; set; }
    }
}